-- MySQL Script generated by MySQL Workbench
-- 06/01/17 13:56:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema enigma
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `enigma` ;

-- -----------------------------------------------------
-- Schema enigma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enigma` DEFAULT CHARACTER SET utf8 ;
USE `enigma` ;

-- -----------------------------------------------------
-- Table `enigma`.`Riddle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `enigma`.`Riddle` ;

CREATE TABLE IF NOT EXISTS `enigma`.`Riddle` (
  `idRiddle` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Question` TEXT(500) NOT NULL,
  `Answer1` TEXT(250) NOT NULL,
  `Answer2` TEXT(250) NULL,
  `Answer3` TEXT(250) NULL,
  PRIMARY KEY (`idRiddle`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
